FROM node:18-slim

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY server/package*.json ./server/

RUN cd server && npm install --only=production

COPY server/ ./server/

EXPOSE 8000

# Start the Express server
CMD ["node", "server/index.js"]