FROM node:18-slim

# Install necessary packages and Google Cloud SDK
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl git vim net-tools build-essential

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN apt-get update && apt-get install -y google-cloud-cli=473.0.0-0

# Set the working directory
WORKDIR /app

# Install Node.js dependencies and copy the rest of the application code
COPY server/package*.json ./server/

RUN cd server && npm install

COPY client/package*.json ./client/

RUN cd client && npm install

COPY . .

# RUN npm run build -> Extra command for react or vite

EXPOSE 5173 8000

CMD ["npm", "run", "dev"]
