apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tax-deployed-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/secure-taxpayer-application/tax-deployed/tax-deployed:latest
          env:
            - name: MONGO_URL
              value: "mongodb+srv://bhesaniyaheena:qlT5BdfbgBrT1wXx@cluster0.rmtff.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: JWT_SECRET
              value: "SKWJOJIWDMKM"
          ports:
            - containerPort: 8000